;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	counsel-find-file
	electric-newline-and-maybe-indent
	elpy-nav-backward-indent
	elpy-nav-forward-indent
	indent-for-tab-command
	kill-region
	org-beginning-of-line
	org-end-of-line
	org-kill-line
	org-return-indent
	org-self-insert-command
	org-shiftright
	org-yank
	tab-to-tab-stop
	yaml-electric-backspace
	yaml-electric-dash-and-dot
	))

(setq mc/cmds-to-run-once
      '(
	keyboard-escape-quit
	org-cycle
	))
